---
- hosts: todohttp
  vars:
    todoapp_user_name: todoapp
    web_app_repository: https://github.com/timoguic/ACIT4640-todo-app.git
  tasks:
    - name: Copying install_todoapp.sh Installer
      become: true
      copy:
        src: files/install_todoapp.sh
        dest: /tmp/install_todoapp.sh
    - name: Importing NodeJS Source
      become: true
      shell: "curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -"
    - name: Installing Packages
      become: true
      package:
        name: "{{item}}"
        state: present
      with_items:
        - nginx
        - git
        - nodejs
    - name: Copying Nginx Configuration
      become: true
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
    - name: Creating Todoapp user
      become: true
      user:
        name: "{{todoapp_user_name}}"
    - name: Running Todoapp Installer
      become: true
      shell: "-u {{todoapp_user_name}} bash /tmp/install_todoapp.sh"
    - name: Reload Nginx with new configuration
      become: true
      service:
        name: nginx
        state: reloaded
        enabled: yes