---
- hosts: todoapp
  become: yes
  vars:
    todoapp_user_name: todoapp
    web_app_repository: https://github.com/timoguic/ACIT4640-todo-app.git
  tasks:
    - name: Importing NodeJS Repository
      get_url:
        url: https://rpm.nodesource.com/setup_14.x
        dest: /tmp/nodejs_repo
      register: nodejs_repo_script
    - name: Setting up NodeJS Repo
      when: nodejs_repo_script.changed
      shell: bash /tmp/nodejs_repo
    - name: Verifying Installation of required Packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - nodejs
    - name: Verifying user todoapp
      user:
        name: "{{ todoapp_user_name }}"
    - name: Verifying Permission for todoapp folder
      become_user: "{{ todoapp_user_name }}"
      file:
        path: /home/{{ todoapp_user_name }}
        mode: "0755"
    - name: Importing Git Repo
      become_user: "{{ todoapp_user_name }}"
      git:
        repo: "{{ web_app_repository }}"
        dest: /home/{{ todoapp_user_name }}/app
        force: yes
    - name: Templating todoapp service
      template:
        src: service.j2
        dest: /etc/systemd/system/todoapp.service
    - name: Installing NPM Modules
      become_user: "{{ todoapp_user_name }}"
      shell: npm install
      args:
        chdir: /home/{{ todoapp_user_name}}/app
    - name: Changing DB Settings for todoapp
      become_user: "{{ todoapp_user_name }}"
      replace:
        path: /home/{{ todoapp_user_name }}/app/config/database.js
        regexp: "localhost/CHANGEME"
        replace: "192.168.150.20/ACIT4640"
    - name: Enable & Start TodoApp
      systemd:
        name: todoapp
        state: started
        enabled: yes
    - name: Opening NodeJS Port (8080)
      firewalld:
        port: 8080/tcp
        state: enabled
        permanent: yes
        immediate: yes