---
- hosts: todohttp
  become: yes
  vars:
    todoapp_user_name: todoapp
  tasks:
    - name: Verifying Installation of required Packages
      package:
        name: nginx
        state: present
    - name: Configuring Nginx.conf
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
    - name: Enable & Start Nginx
      systemd:
        name: nginx
        enabled: yes
        state: started