---
- hosts: tododb
  become: yes
  vars:
    todoapp_user_name: todoapp
  tasks:
    - name: Importing MongoDB Repository
      copy:
        src: mongorepo.txt
        dest: /etc/yum.repos.d/mongodb-org-4.4.repo
    - name: Verifying Installation of required Packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - tar
        - mongodb-org
    - name: Allowing Mongo to listen on all interfaces
      replace:
        path: /etc/mongod.conf
        regexp: "bindIp: 127.0.0.1"
        replace: "bindIp: 0.0.0.0"
    - name: Enable & Start MongoDB
      systemd:
        name: mongod
        enabled: yes
        state: started
    - name: Downloading MongoDB Pre-Loaded Data
      get_url: 
        url: https://acit4640.y.vu/docs/module06/resources/mongodb_ACIT4640.tgz
        dest: /tmp/mongod_export.tgz
        username: student
        password: BCIT2020
      register: download_mongo_export
    - name: Extracting Data
      when: download_mongo_export.changed
      unarchive:
        remote_src: yes
        src: /tmp/mongod_export.tgz
        dest: /tmp
      register: unpack_mongo_data
    - name: Import Pre-Load Data
      when: unpack_mongo_data.changed
      shell: mongorestore -d ACIT4640 /tmp/ACIT4640
    - name: Opening MongoDB Port (27017)
      firewalld:
        port: 27017/tcp
        state: enabled
        permanent: yes
        immediate: yes